<section class="intro">
	<figure><img src="public/images/code.jpg" alt="Code html"></figure>
	<h1>A propos de moi</h1>
	<p>Après des études supérieures en chimie, j'ai travaillé plusieurs années dans la recherche scientifique en France et à l'étranger. J'ai ensuite décidé de me réorienter vers le métier de développeur intégrateur web. J'ai donc suivi une formation intensive à la <a href="http://www.3wa.fr">3W Academy</a> à Strasbourg.</p>
</section>
<section class="clearfix">
	<h2>Technologies maitrisées</h2>
	<div class="clearfix">
		<div class="tech inte">
			<div class="container zoom">
				<h3>HTML5</h3>
				<img src="public/images/html.png" alt="logo html">
				<p>Structure de base</p>
				<div class="bar100">
					<div class="bar"></div>
				</div>
			</div>
		</div>
		<div class="tech inte">
			<div class="container zoom">
				<h3>CSS3</h3>
				<img src="public/images/css3.png" alt="logo css">
				<p>Style</p>
				<div class="bar100">
					<div class="bar"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="clearfix">
		<div class="tech dev">
			<div class="container zoom">
				<h3>PHP</h3>
				<img src="public/images/php.png" alt="logo php">
				<p>MVC2 strict et objets pour un site dynamique</p>
				<div class="bar100">
					<div class="bar"></div>
				</div>
			</div>
		</div>
		<div class="tech dev">
			<div class="container zoom">
				<h3>JavaScript</h3>
				<img src="public/images/js.png" alt="logo js">
				<p>Pour une expérience interactive</p>
				<div class="bar75">
					<div class="bar"></div>
				</div>
			</div>
		</div>
		<div class="tech dev">
			<div class="container zoom">
				<h3>MySQL</h3>
				<img src="public/images/MySQL.png" alt="logo mysql">
				<p>Utilisation de bases de données en lien avec PHP</p>
				<div class="bar75">
					<div class="bar"></div>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="clearfix">
	<h2>Autres notions vues</h2>
	<div class="owl-carousel misc">
		<div class="container">
			<img src="public/images/Bootstrap.png" alt="logo bootstrap">
			<h4>Bootstrap</h4>
		</div>
		<div class="container">
			<img src="public/images/wordpress.png" alt="logo wordpress">
			<h4>Wordpress</h4>
		</div>
		<div class="container">
			<img src="public/images/jquery.png" alt="logo JQuery">
			<h4>JQuery</h4>
		</div>
		<div class="container">
			<img src="public/images/ajax.png" alt="logo ajax">
			<h4>Ajax</h4>
		</div>
		<div class="container">
			<img src="public/images/nodejs.png" alt="logo nodeJS">
			<h4>NodeJS</h4>
		</div>
		<div class="container">
			<img src="public/images/symfony.png" alt="logo symfony">
			<h4>Symfony2</h4>
		</div>
	</div>
</section>
<section class="qualite">
	<h2>Principales qualités</h2>
	<ul>
		<li>Rigueur scientifique</li>
		<li>Esprit synthétique</li>
		<li>Adaptable</li>
	</ul>
</section>