<h1>Veuillez vous connecter pour continuer</h1>
<div class="error"><?=$error?></div>
<form action="" method="POST" class="clearfix login">
	<div class="login_item">
		<label for="login">Login</label>
		<input type="text" name="login" id="login">
	</div>
	<div class="login_item">
		<label for="pass">Mot de passe</label>
		<input type="password" name="pass" id="pass">
	</div>
	<div class="login_item">
		<button class="btn" type="submit">Se connecter</button>
	</div>
</form>