<h1>Merci de votre intérêt !</h1>
<p>Votre message a bien été envoyé.</p>
<figure class="poste">
	<img src="public/images/Poste_centrale_de_strasbourg.jpg" alt="Poste centrale de Strasbourg">
	<caption><a href="http://www.flickr.com/photos/panr/4510410738/">Poste centrale de Strasbourg</a>, <a href="http://www.flickr.com/photos/21678559@N06">Robert Cutts</a>, <a href="https://creativecommons.org/licenses/by/2.0/deed.en">cc-by-2.0</a></caption>
</figure>