<h1>Me contacter</h1>
<form action="" method="POST" class="clearfix contact">
	<div class="error"><?=$error?></div>
	<div class="contact_item">
		<label for="name">Nom* : </label>
		<input type="text" name="name" id="name" required>
	</div>
	<div class="contact_item">
		<label for="email">Email* : </label>
		<input type="email" name="email" id="email" required>
	</div>
	<div class="contact_item">
		<label for="tel">Téléphone :</label>
		<input type="text" name="tel" id="tel">
	</div>
	<div class="contact_item">
		<label for="society">Société :</label>
		<input type="text" name="society" id="society">
	</div>
	<div class="contact_item">
		<label for="title">Titre du message* : </label>
		<input type="text" name="title" id="title" required>
	</div>
	<div class="contact_item">
		<label for="content">Votre message* : </label>
		<textarea name="content" id="content" rows="10" required></textarea>
	</div>
	<div class="contact_item">
		<button class="btn" type="submit">Envoyer</button>
	</div>
	<div class="notice">* champs obligatoires</div>
</form>
<div class="mail"><i class="fa fa-envelope" aria-hidden="true"></i> <a href="mailto:contact@gael-benay.fr">contact@gael-benay.fr</a></div>