<nav>
	<ul>
		<li><a href=".">Accueil</a></li>
		<li><a href="a_propos">A propos</a></li>
		<li><a href="travaux">Travaux</a></li>
		<li><a href="contact">Contact</a></li>
	</ul>
</nav>
<div class="share">
	<a href="http://www.linkedin.com/in/gael-benay-708a3213a" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
	<a href="http://www.viadeo.com/p/002qmp7qn687un0" target="_blank"><i class="fa fa-viadeo" aria-hidden="true"></i></a>
</div>
<p>Portfolio de Gaël Benay - 2016</p>