<h1>Gaël Benay</h1>
<h2>Développeur intégrateur web</h2>
<section class="clearfix">
	<article class="col">
		<a href="a_propos">
			<div class="container zoom">
				<h3>A propos de moi</h3>
				<img src="public/images/Gael.jpg" alt="le développeur">
				<p>Apprenez à me connaitre</p>
			</div>
		</a>
	</article>
	<article class="col">
		<a href="travaux">
			<div class="container zoom">
				<h3>Mes réalisations</h3>
				<img src="public/images/works.png" alt="travaux">
				<p>Découvrez certains des travaux auxquels j'ai contribué</p>
			</div>
		</a>
	</article>
	<article class="col">
		<a href="contact">
			<div class="container zoom">
				<h3>Me contacter</h3>
				<img src="public/images/Contact.png" alt="contact">
				<p>Laissez moi un message</p>
			</div>
		</a>
	</article>
</section>
<aside class="chat_container">
	<?php require('apps/chat.php'); ?>
</aside>