<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<base href="http://www.gael-benay.fr/">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="public/styles/reset.css">
	<link rel="stylesheet" href="public/styles/owl.carousel.min.css">
	<link href="https://fonts.googleapis.com/css?family=Amiko|Roboto" rel="stylesheet">
	<link rel="stylesheet" href="public/styles/font-awesome.min.css">
	<link rel="stylesheet" href="public/styles/style.css">
	<script src="public/scripts/prefixfree.min.js"></script>
	<title>Portfolio Gael Benay</title>
	<meta name="description" content="Portfolio de Gael Benay, développeur intégrateur web à Strasbourg. Ce site montre des travaux réalisés durant la formation à la 3W Academy.">
	<meta name="keywords" content="portfolio, gael benay, developpeur integrateur web, 3WA, Strasbourg">
	<script src="public/scripts/jquery.js"></script>
	<script src="public/scripts/owl.carousel.min.js"></script>
	<script src="public/scripts/script.js"></script>
</head>
<body>
	<header class="header">
		<?php require('apps/header.php'); ?>
	</header>
	<main class="main">
		<?php require('apps/content.php'); ?>
	</main>
	<footer class="footer">
		<?php require('apps/footer.php'); ?>
	</footer>
</body>
</html>